#!/bin/sh

# Preview script built for use with lf and fzf
#LINES=30





# Script arguments
FILE_PATH="${1}"         # Full path of the highlighted file
HEIGHT="${2}"





case "$1" in
    *.png|*.jpg|*.jpeg|*.mkv|*.mp4) chafa --fill=block --symbols=block -c 256 -s 60x"${HEIGHT}" "${FILE_PATH}" || exit 1;; #mediainfo "$1";;
    *.md) glow -s dark "$1";;
    *.pdf) pdftotext "$1" -;;
    *.zip) zipinfo "$1";;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1";;
    #*.rar) unrar l "$1";;
    #*.7z) 7z l "$1";;
    #*.html|*.xml) w3m -dump "$1";;
    #*.zsh*|*.bash*|*.git*) pistol "$1";;
    *) bat "$1" --color always --theme "Monokai Extended Origin" # highlight "$1" -O truecolor --force;;
esac
