#!/bin/sh

alias wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\""
# alias docker='docker info &> /dev/null || {docker_setup && eval $(docker-machine env default)} && docker'
alias matlab='matlab -nosplash -nodesktop'
alias simulink='matlab -r simulink' # start_simulink slLibraryBrowser
alias ncdu='ncdu --exclude-firmlinks --si --color dark -x'
# alias wal='wal --cols16 lighten --backend wal && xrdb -merge ~/.cache/wal/colors.Xresources' # --backend haishoku always clear cache or 'lighten' vs 'darken' won't be used
alias diff='diff -bur --color'
# https://docs.docker.com/reference/cli/docker/container/ls/#format
alias dps='docker ps --format "table {{.ID}},{{.Names}},{{.Networks}}" | column -t -s","'
alias wine='sudo sysctl dev.i915.perf_stream_paranoid=0 && WINEDEBUG="fixme-all" WINEARCH=win64 WINEPREFIX=~/.config/wine wine'
alias feh='feh --no-fehbg'
# alias rofi='rofi -dpi 0'
alias ls='ls -v' # shows dotfiles first
alias zathura='zathura --fork'
alias gsub="git submodule"
alias gsubu="git submodule update --init --recursive --remote"

alias sudo='sudo -E -s'

alias nixdevgui='nix develop -k DISPLAY -k XAUTHORITY -k XDG_CACHE_HOME -i'


# from old aliasrc
# alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
# alias ssh='kssh() {[ "$TERM" = "xterm-kitty" ] && kitty +kitten ssh $@ || ssh $@}; kssh'
# # alias docker='docker info &> /dev/null || {docker_setup && eval $(docker-machine env default)} && docker'
# alias quartus='/opt/altera/15.0/quartus/bin/quartus --64bin &>/dev/null & disown'
# alias modelsim='/opt/altera/15.0/modelsim_ase/linuxaloem/vsim &>/dev/null & disown'
# alias matlab='matlab -nosplash -nodesktop'
# alias simulink='matlab -r simulink' # start_simulink slLibraryBrowser
# alias ncdu='ncdu --exclude-firmlinks --si --color dark -x'
