#!/bin/sh

# load X resources
[ -f ~/.config/X11/Xresources ] && xrdb -merge -I$HOME ~/.config/X11/Xresources

# set configurations for native display
[ -f ~/.local/bin/xrandr.py   ] && ~/.local/bin/xrandr.py 1 &>/dev/null

# set keybinding hack for firefox
[ -f ~/.config/xbindkeys/config ] && xbindkeys -f ~/.config/xbindkeys/config

# set key remappings
# [ -f ~/.config/X11/Xmodmap ] && xmodmap ~/.config/X11/Xmodmap

# start redshift
redshift &

# start window manager
exec i3
