#!/bin/sh

# TODO: find out if we even need these
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto


# load X resources
#[ -f ~/.config/x11/Xresources ] && xrdb -merge -I$HOME ~/.config/x11/Xresources

# set configurations for native display
#[ -f ~/.local/bin/xrandr.py   ] && ~/.local/bin/xrandr.py 1 &>/dev/null

# invoke global X session script
# . /etc/X11/Xsession
. /etc/X11/Xsession.d/20dbus_xdg-runtime

# set up monitor
xrandr --output HDMI-2 --mode 3440x1440 --right-of eDP-1

# set natural scrolling
xinput list --id-only | xargs -n1 -I{} xinput --set-prop {} "libinput Natural Scrolling Enabled" 1 &>/dev/null

# set mouse speed and acceleration
xinput set-prop 'Logitech M510' "libinput Accel Speed" -0.2
#xinput list --id-only | xargs -n1 -I{} xinput --set-prop {} "libinput Accel Speed" -0.60 &>/dev/null
#xinput list --id-only | xargs -n1 -I{} xinput --set-prop {} "libinput Accel Profile Enabled" 1,0 &>/dev/null
#xset m 3/1 0

# set key repeat relay (225 ms) and repeat time (30 ms -> ~33/s)
xset r rate 225 33

# start redshift
[ -x "$(command -v redshift)" ] && redshift &

# set cursor
xsetroot -cursor_name left_ptr

# set wallpaper
# feh --bg-fill ~/Downloads/torc_robotics_bg_black_1920x1080.v1.png
feh --bg-fill $HOME/.local/share/wallpapers/beams.jpeg

# feh --bg-fill ~/Documents/whatsapp.jpg
# feh --bg-fill ~/Projects/userdata/wallpapers/beams.jpeg

# start window compositor
[ -x "$(command -v picom)" ] && picom --config ~/.config/picom/picom.conf &

# sleep 1

# start polybar
[ -x "$(command -v polybar)" ] && ~/.config/polybar/launch.sh &

# xset s 300 5
# xss-lock -n /usr/lib/xsecurelock/dimmer -l -- /home/skipper/xsecurelock.sh

# start window manager
sxhkd &
exec bspwm
