#!/bin/sh

# set true DPI based on screen dimensions
xrandr | grep -w connected | grep -o '[0-9]\+mm' | sed 's/mm//g' \
       | paste -sd 'x' - | xargs xrandr --fbmm;
TRUDPI=$(xdpyinfo | grep resolution | grep -o '[0-9]\+x' | sed 's/x//g')

# adjust dpi based on how much space you want the bar to take ip
# we want a bar BARHGT true-dpi-inches tall to take up BARPCT % of the screen
BARPCT=2.25; BARHGT_IN=0.25
WINHGT_IN=$(xrandr | grep -w connected | awk '{print $NF}' | sed 's/mm//g' \
                   | xargs -I{} echo '0.0393701*{}' | bc)
DPI=$(calc "ceil($BARPCT/100*$WINHGT_IN*$TRUDPI/$BARHGT_IN)//24 * 24")
DPI=$(calc "max($DPI, 96)")

# set DPI
xrandr --dpi $DPI

# load X resources
[ -f $XDG_CONFIG_HOME/x11/Xresources ] \
  && { xrdb -merge -I$HOME $XDG_CONFIG_HOME/x11/Xresources; }

# ensure xresources is aligned with xrandr/xdpyinfo
xdpyinfo \
  | grep resolution \
  | grep -o '[0-9]\+x' \
  | sed 's/x//g;s/^/Xft.dpi: /g' \
  | xrdb -merge -;

xrdb -merge ~/.cache/wal/colors.Xresources

# based on /etc/X11/Xsession.d/20dbus_xdg-runtime in ubuntu desktop
DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
dbus-update-activation-environment --verbose --systemd \
  DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# set natural scrolling
xinput list --id-only \
  | xargs -I{} \
      xinput set-prop {} "libinput Natural Scrolling Enabled" 1 &>/dev/null

# set mouse speed and acceleration
# TODO: fix
# xinput list --id-only \
#   | xargs -I{} xinput set-prop {} "libinput Accel Speed" -0.60 &>/dev/null
# xinput list --id-only \
#   | xargs -I{} xinput set-prop {} "libinput Accel Profile Enabled" 1,0 &>/dev/null

# set key repeat relay (225 ms) and repeat time (30 ms -> ~33 reapeats/s)
xset r rate 225 33 # TODO: adjust

# start redshift
redshift &

# set cursor
xsetroot -cursor_name left_ptr

# set wallpaper
feh --bg-fill $HOME/.local/share/wallpapers/beams.jpeg

# start window compositor
picom --config ~/.config/picom/picom.conf &

# start polybar
~/.config/polybar/launch.sh &

# start window manager
sxhkd &
exec bspwm
