#!/bin/sh

# load X resources
[ -f ~/.config/X11/Xresources ] && xrdb -merge -I$HOME ~/.config/X11/Xresources

# set configurations for native display
[ -f ~/.local/bin/xrandr.py   ] && ~/.local/bin/xrandr.py 1 &>/dev/null

# set keybinding hack for firefox
[ -f ~/.config/xbindkeys/config ] && xbindkeys -f ~/.config/xbindkeys/config

# set key remappings
# [ -f ~/.config/X11/Xmodmap ] && xmodmap ~/.config/X11/Xmodmap

# start redshift
redshift &

# set cursor
xsetroot -cursor_name left_ptr &

# set wallpaper
feh --bg-fill $HOME/.local/share/wallpapers/beams.jpeg &

# set xbindkeys
xbindkeys -f ~/.config/xbindkeys/config &

# set compton for window opacity
# compton --config $HOME/.config/compton/compton.conf &

# start window manager
sxhkd &
exec bspwm
# exec i3
