# set display configuration
autorandr --change --force || xrandr --auto

# load X resources
xrdb -merge $XDG_CONFIG_HOME/x11/Xresources
xrdb -merge $XDG_CACHE_HOME/wal/colors.Xresources

# pass environment to dbus
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

# start redshift
redshift &

# start window compositor
picom --config ~/.config/picom/picom.conf &

# start window manager
sxhkd &
exec bspwm
