#!/bin/sh

# Set a custom wallpaper image
WALLPAPER="$HOME/.local/share/wallpapers/beams.jpeg"
osascript -e "tell application \"Finder\" to set desktop picture to \"$(realpath "$WALLPAPER")\" as POSIX file"
osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"$(realpath "$WALLPAPER")\""

# osx settings
# yabai -m signal --add event= action="$HOME/.config/osx/defaults"
# ("$HOME/.config/osx/dock" && killall Dock) &

# global settings
yabai -m config mouse_follows_focus          off #on
yabai -m config focus_follows_mouse          off #autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         0
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xffa89984
yabai -m config normal_window_border_color   0xff3c3836
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  40
yabai -m config bottom_padding               40
yabai -m config left_padding                 40
yabai -m config right_padding                40
yabai -m config window_gap                   10


# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off

# yabai -m rule --add app="Code" display=2
# yabai -m rule --add app="kitty" display=3
# yabai -m rule --add app="Brave Browser" display=1

yabai -m signal --add event=mission_control_enter action="skhd -k \"ctrl - m\""
yabai -m signal --add event=mission_control_exit  action="skhd -k \"ctrl - m\""

# ensure dmenu, ubersicht bar, and redshift are running
pgrep dmenu-mac &>/dev/null || open -a dmenu-mac
pgrep Übersicht &>/dev/null || open -a Übersicht
pgrep redshift  &>/dev/null || redshift &

echo "yabai configuration loaded.."

# BIG BIG BIG
# rule: if app opened, move to display of current focus?
# rule: on window close, stay on desktop
# yabai -m signal --add event=window_destroyed action=""
