#!/bin/sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#===============================================================================
# DESKTOP ENV SETUP
#===============================================================================

# Set a custom wallpaper image
WALLPAPER="$HOME/.local/share/wallpapers/beams.jpeg"
osascript -e "tell application \"Finder\" to set desktop picture to \"$(realpath "$WALLPAPER")\" as POSIX file"
osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"$(realpath "$WALLPAPER")\" as POSIX file"

# ensure dmenu, ubersicht bar, and redshift are running
pgrep dmenu-mac &>/dev/null || open -a dmenu-mac
pgrep redshift  &>/dev/null || redshift &
pgrep spacebar  &>/dev/null || spacebar &

#===============================================================================
# WM SETUP
#===============================================================================

source ~/.cache/wal/colors.sh # load pywal environment variables

# get colors from environment variables
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3     | sed 's/#//')
CNORM=$(echo $color1     | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')


yabai -m config layout                  bsp
yabai -m config window_placement        second_child
yabai -m config split_ratio             0.50
yabai -m config auto_balance            off

yabai -m config insert_feedback_color      0xff$CINSE

# window settings
yabai -m config window_opacity_duration 0.0
yabai -m config window_opacity          on
yabai -m config active_window_opacity   1.0
# yabai -m config normal_window_opacity   0.9
yabai -m config normal_window_opacity   0.90196078431
yabai -m config window_shadow           off

# mouse actions
yabai -m config mouse_follows_focus     on
yabai -m config focus_follows_mouse     autoraise
yabai -m config mouse_modifier          fn
yabai -m config mouse_action1           move
yabai -m config mouse_action2           resize
yabai -m config mouse_drop_action       swap

# general space settings
yabai -m config external_bar all:26:0
yabai -m config top_padding             15
yabai -m config bottom_padding          15
yabai -m config left_padding            15
yabai -m config right_padding           15
yabai -m config window_gap              15
