#!/bin/sh

# source ~/.cache/wal/colors.sh # load pywal environment variables
#
# # get colors from environment variables
# CBACK=$(echo $background | sed 's/#//')
# CFORE=$(echo $foreground | sed 's/#//')
# CACTV=$(echo $color3     | sed 's/#//')
# CNORM=$(echo $color1     | sed 's/#//')
# CINSE=$(echo $foreground | sed 's/#//')


source ~/.local/src/gruvbox-contrib/shell/colors.sh # load pywal environment variables

# get colors from environment variables
CBACK=$(echo $dark0_hard | sed 's/#//')
CFORE=$(echo $light1 | sed 's/#//')
# CACTV=$(echo $color3     | sed 's/#//')
CNORM=$(echo $bright_red     | sed 's/#//')


spacebar -m config text_font         "Hack Nerd Font Mono:Regular:12.0"
spacebar -m config icon_font         "Hack Nerd Font:Regular:14.0"
spacebar -m config background_color  0xe6$CBACK
spacebar -m config foreground_color  0xff$CFORE
spacebar -m config space_icon_color  0xff$CNORM
spacebar -m config space_icon_strip  1 2 3 4 5 6 7 8 9 10 # I II III IV V VI VII VIII IX X
spacebar -m config power_icon_strip   
spacebar -m config space_icon        
spacebar -m config clock_icon        " "
spacebar -m config clock_format      " %a %b %d %I:%M %p"
