#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
# mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

# if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
#   xrandr --output "$mainmonitor" --auto --output LVDS1 --off
# fi

# Start workspaces on the main monitor.
# bspc monitor "$mainmonitor" -d 1 2 3 4 5 6 7 8 9 10
bspc monitor "eDP-1"  -d 1 2
bspc monitor "HDMI-2" -d 3 4
# bspc monitor "HDMI-2" -d 3



bspc desktop -f 1


###---Global Settings---###
bspc config automatic_scheme           alternate
bspc config initial_polarity           second_child
bspc config pointer_modifier           lock
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config click_to_focus             none
bspc config focus_follows_pointer      true
bspc config pointer_follows_focus      true
bspc config pointer_follows_monitor    true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc rule -a Zathura state=tiled


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
# bspc config normal_border_color "$background"
# bspc config active_border_color "$background"
bspc config normal_border_color "$color7"
bspc config active_border_color "$color7"
bspc config focused_border_color "$color7"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color7"



# bspc config normal_border_color        "#32302f"
# bspc config active_border_color        "#32302f"
# bspc config focused_border_color       "#ebdbb2"
# bspc config presel_feedback_color      "#32302f"
# bspc config urgent_border_color        "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding    15
bspc config bottom_padding 15
bspc config left_padding   15
bspc config right_padding  15
bspc config border_width   2
bspc config window_gap     15
