live_config_reload = true
working_directory = "None"

import = [
    # "~/.config/alacritty/themes/gruvbox_dark.toml"
    # "~/.cache/wal/colors.toml"
    "~/.cache/wal/colors-alacritty.toml"
]

[cursor]
style = {shape = "Beam", blinking = "Never"}
unfocused_hollow = true


# [cursor.vi_mode_style]
# shape = "Beam"
# blinking = "Always"
# unfocused_hollow = true



# NOTE: this works too
# [cursor.style]
# shape = "Beam"
# blinking = "Never"


# [[colors.indexed_colors]]
# color = "0xfe8019"
# index = 16
#
# [[colors.indexed_colors]]
# color = "0xd65d0e"
# index = 17
#
# [[colors.indexed_colors]]
# color = "0x3c3836"
# index = 18
#
# [[colors.indexed_colors]]
# color = "0x504945"
# index = 19
#
# [[colors.indexed_colors]]
# color = "0xbdae93"
# index = 20
#
# [[colors.indexed_colors]]
# color = "0xebdbb2"
# index = 21
#
# [colors.bright]
# black = "0x665c54"
# blue = "0xbdae93"
# cyan = "0xd65d0e"
# green = "0x3c3836"
# magenta = "0xebdbb2"
# red = "0xfe8019"
# white = "0xfbf1c7"
# yellow = "0x504945"
#
# [colors.cursor]
# cursor = "0xd5c4a1"
# text = "0x32302f"
#
# [colors.normal]
# black = "0x32302f"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xd5c4a1"
# yellow = "0xfabd2f"
#
# [colors.primary]
# background = "0x32302f"
# foreground = "0xd5c4a1"
#
# [colors.selection]
# background = "0x665c54"
# text = "CellForeground"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

# [env]
# WINIT_X11_SCALE_FACTOR = "2.0"

[font]
size = 15.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# TODO: ls <DIRNAME> -la (as opposed to ls -la <DIRNAME>) does not work in login shells
# TODO: when shell is not configured, a login shell is used by default, but new terminals
# print a message 'Last login: <date> on <tty>'
[shell]
program = "/bin/zsh"
# args = ["-l"]

[window]
decorations = "none"
dynamic_padding = false
# option_as_alt = "Both" # TODO: should be in soon: https://github.com/alacritty/alacritty/pull/7601
startup_mode = "Windowed"

[window.padding]
x = 4
y = 4

[window.position]
x = 0
y = 0
